### ISSUE TITLE
Wrong character in file

### ISSUE THREAD

**Issue by mlforcada** [aoliverg/PosEdiOn#1]
https://github.com/aoliverg/PosEdiOn/blob/295c80274e22998d3ca4cb4ec57b9df0cc78a826/PosEdiOn.py#L301

There is a ŧ where you should have a t.

And it bombs:

python PosEdiOn.py 
  File "PosEdiOn.py", line 301
SyntaxError: Non-ASCII character '\xc5' in file PosEdiOn.py on line 301, but no encoding declared; see http://python.org/dev/peps/pep-0263/ for details

**Comment by mlforcada** [comment]
Once solved, I run into another problem with "import tkinter as tk". 
There are no instructions to install or run!

**Comment by aoliverg** [comment]
Thank you for the comment. The ŧ issue is corrected now. The program should be run with python3 . From the error message I suppose that you're using Python 2.

I will document the program in a couple of days. Sorry for that!

**Comment by mlforcada** [comment]
You're right, but:
$ python3 PosEdiOn.py 
Traceback (most recent call last):
  File "PosEdiOn.py", line 21, in <module>
    from chronometer import Chronometer
ModuleNotFoundError: No module named 'chronometer'

**Comment by aoliverg** [comment]
I will add a requirements files soon to easy the installation of libraries and modules. In general, if this kind of errors appear the installation can be done with pip3

sudo pip3 install chronometer

and the same for other missing packages.

**Comment by mlforcada** [comment]
pyinput and pyperclip. How about saying this in the README.md?

**Comment by mlforcada** [comment]
When running 

python3 PosEdiOn.py

without any parameters it would be great if the program gave a usage message instead of a file-not-found error!

**Comment by mlforcada** [comment]
Examples of files such as the ones cited in config.yaml would really help.

**Comment by aoliverg** [comment]
Sorry, an initial file to start the program has been added.
